// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdHocMemoryNoteStatus = { path: string, content: string, reason: string | null, durableMatches: Array<string>, };
