// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

export type BtwStartParams = { btwId: string, threadId: string, question: string, model?: string | null, serviceTier?: string | null, effort?: ReasoningEffort | null, };
