// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadFileHistoryRestoreParams = { threadId: string,
/**
 * Restore tracked file changes made by the last N user turns. Must be >= 1.
 */
numTurns: number, };
